apiVersion: apps/v1
kind: Deployment
metadata:
  name: minprog-ide
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: minprog-ide
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: minprog-ide
    spec:
      containers:
        - name: minprog-ide
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: IDE_VERSION
              value: "{{ .Chart.AppVersion }}"