{{- if .Values.azure }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: minprog-identity-aks-kv-binding
  namespace: "{{ .Release.Namespace }}"
spec:
  azureIdentity: minprog-identity-aks-kv
  selector: minprog-azure-kv
{{- end }}
